DROP TABLE IF EXISTS BOOK_INVENTORY;
DROP TABLE IF EXISTS BOOK_INVENTORY2;


CREATE TABLE BOOK_INVENTORY(
		BOOKID INTEGER PRIMARY KEY AUTO_INCREMENT,
		TITLE VARCHAR(100) NOT NULL,
		AUTHOR VARCHAR(100) NOT NULL,
		ISBN INTEGER NOT NULL, 
		AVAILIBILITY VARCHAR(1) NOT NULL
);

CREATE TABLE BOOK_INVENTORY2(
		ISBN INTEGER PRIMARY KEY,
		CATEGORY VARCHAR(100) NOT NULL,
		PUBLISHED DATE NOT NULL
);




